[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre.workspace = true
color-eyre.workspace = true

clap.workspace = true
clap-verbosity.workspace = true

tracing-log.workspace = true
tracing-subscriber.workspace = true

config = { version = "0.15.19" }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.140", default-features = false }

# protobuf
tonic.workspace = true
tokio.workspace = true

# local
proto.path = "../crates/proto"
ui.path = "../crates/ui"